---
- name: AD join - Red Hat
  hosts: all
  gather_facts: false
  vars_files:
    - vault.yml

  roles:
  - role: adjoin-RH
    ad_groups: RKT_Users
    domain_ou_path: OU=Non-Windows,OU=Servers,OU=RKT,DC=TEST,DC=LOCAL