---
- hosts: all
  gather_facts: true
  tasks:

  - name: install packages Ubuntu
    apt:
      name: 
        - apache2
        - nano
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: install packages RedHat
    yum:
      name: 
        - httpd
        - nano
      state: present
    when: ansible_distribution == "RedHat"

  - name: Start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "RedHat"
